# Site settings
title: Drawkle
email: cacayperez@outlook.com
url: https://example.github.io
description: "A website of Cacay Perez"
# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static
about: "Some description here for me to test"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 24749E
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Cacay Perez
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/xcacay
  - title: pinterest
    url: https://www.pinterest.com/cacayp
  - title: behance
    url: https://www.behance.net/cacay
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Rizal
  - line: Philippines

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: /blog/post/:title
encoding: utf-8

paginate: 5
paginate_path: "/blog/:num/"
gems:
  - jekyll-archives
